# Generated by Django 5.2.3 on 2025-06-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_grade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='student',
            new_name='name',
        ),
    ]
